---
name: ci

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v2
      - run: make check
